# Generated by Django 3.2.3 on 2021-12-13 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_reg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_name', models.CharField(default='', max_length=300)),
                ('Mail_id', models.CharField(default='', max_length=200)),
                ('gender', models.CharField(default='', max_length=200)),
                ('Password', models.CharField(default='', max_length=300)),
                ('Confirm_password', models.CharField(default='', max_length=300)),
                ('std_type', models.CharField(default='', max_length=300)),
            ],
        ),
    ]
