# Generated by Django 3.2.3 on 2021-12-13 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_task', models.CharField(default='', max_length=300)),
                ('percentage', models.CharField(default='', max_length=300)),
                ('dates', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
