# Generated by Django 3.2.3 on 2021-12-13 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ToDo', '0003_rename_user_task_tasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='task_IDD',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ToDo.user_reg'),
        ),
    ]
